language: node_js
node_js:
  - "0.10"
services:
  - mongodb
env:
  global:
    - NODE_ENV=test
    - COVERALLS_REPO_TOKEN=IYP8L16MHhTpbiZ5dWPkAJQ1dMjg1xt6S
before_script:
  - npm run setup
after_script:
  - cat lcov.info | node ./node_modules/coveralls/bin/coveralls.js