language: node_js
node_js:
  - "0.10"
services:
  - mongodb
env:
  global:
    - NODE_ENV=test
    - COVERALLS_REPO_TOKEN=IYP8L16MHhTpbiZ5dWPkAJQ1dMjg1xt6S
    - CODECLIMATE_REPO_TOKEN=9940f0a450f94f5dda0fb33a2389529ce79888ae1e3e5d13bbb0e92cb2c2aaee
before_script:
  - npm run setup
after_script:
  - cat lcov.info | node ./node_modules/coveralls/bin/coveralls.js
  - cat lcov.info | node ./node_modules/codeclimate-test-reporter/bin/codeclimate.js