language: node_js
node_js:
  - "0.10"
services:
  - mongodb
env:
  global:
    - NODE_ENV=test
before_script:
  - npm run setup
after_script:
  - CODECLIMATE_REPO_TOKEN=IYP8L16MHhTpbiZ5dWPkAJQ1dMjg1xt6S cat lcov.info | node ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < lcov.info
  - cat lcov.info | node ./node_modules/coveralls/bin/coveralls.js