language: node_js
node_js:
  - "0.10"
services:
  - mongodb
env:
  global:
    - NODE_ENV=test
before_script:
  - npm run setup
addons:
  code_climate:
    repo_token: IYP8L16MHhTpbiZ5dWPkAJQ1dMjg1xt6S
after_script:
  - cat lcov.info | codeclimate